In [3]:
import json
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import os

# 读取单个JSON文件
def load_json(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)
    return data

# 读取多个JSON文件
def load_multiple_json(paths):
    all_data = []
    for path in paths:
        if os.path.exists(path):
            data = load_json(path)
            all_data.append(data)
        else:
            print(f"文件 {path} 不存在")
    return all_data

# 计算TF-IDF相似度
def compute_tfidf_similarity(texts):
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(texts)
    similarity_matrix = cosine_similarity(tfidf_matrix)
    return similarity_matrix

# 计算所有文件中代码和算法描述的相似度
def compute_code_and_algorithm_similarity(data_list):
    all_code_similarity = []
    all_algorithm_similarity = []
    
    for data in data_list:
        # 提取代码和算法描述
        codes = [entry['code'] for entry in data]
        algorithms = [entry['algorithm'] for entry in data]
        
        # 计算代码的相似度
        code_similarity = compute_tfidf_similarity(codes)
        all_code_similarity.append(code_similarity)
        
        # 计算算法描述的相似度
        algorithm_similarity = compute_tfidf_similarity(algorithms)
        all_algorithm_similarity.append(algorithm_similarity)
    
    return all_code_similarity, all_algorithm_similarity

# 计算相似度的求和指标
def compute_similarity_score(similarity_matrix, include_diagonal=True):
    # 去除对角线元素
    if not include_diagonal:
        np.fill_diagonal(similarity_matrix, 0)
    
    # 求和
    total_similarity = np.sum(similarity_matrix)
    num_elements = similarity_matrix.size
    
    # 平均相似度
    average_similarity = total_similarity / num_elements
    
    return total_similarity, average_similarity

# 主函数
def main():
    # JSON文件路径列表
    paths = ['D:/00_Work/00_CityU/04_AEL_MEC/hle/results/hie/202412241006/sample_log.json',
            'D:/00_Work/00_CityU/04_AEL_MEC/hle/results/hie/202412240058/sample_log.json']  # 这里填入你的路径列表
    
    # 读取多个JSON文件
    data_list = load_multiple_json(paths)
    
    # 计算相似度
    all_code_similarity, all_algorithm_similarity = compute_code_and_algorithm_similarity(data_list)
    
    # 输出结果
    for i, (code_sim, alg_sim) in enumerate(zip(all_code_similarity, all_algorithm_similarity)):
        print(f"对于文件 {paths[i]}:")

        # 输出代码相似度矩阵并计算总体相似度
        print("代码相似度矩阵:")
        print(code_sim)
        total_code_sim, avg_code_sim = compute_similarity_score(code_sim, include_diagonal=False)
        print(f"代码相似度总和 (去除对角线): {total_code_sim}")
        print(f"代码相似度平均值 (去除对角线): {avg_code_sim}")
        
        # 输出算法描述相似度矩阵并计算总体相似度
        print("\n算法描述相似度矩阵:")
        print(alg_sim)
        total_alg_sim, avg_alg_sim = compute_similarity_score(alg_sim, include_diagonal=False)
        print(f"算法描述相似度总和 (去除对角线): {total_alg_sim}")
        print(f"算法描述相似度平均值 (去除对角线): {avg_alg_sim}")

        print("\n" + "-"*50)

if __name__ == "__main__":
    main()


对于文件 D:/00_Work/00_CityU/04_AEL_MEC/hle/results/hie/202412241006/sample_log.json:
代码相似度矩阵:
[[1.         0.39453168 0.22245042 0.3850961  0.34519326]
 [0.39453168 1.         0.17279082 0.31489993 0.24091595]
 [0.22245042 0.17279082 1.         0.24740603 0.2907207 ]
 [0.3850961  0.31489993 0.24740603 1.         0.48463082]
 [0.34519326 0.24091595 0.2907207  0.48463082 1.        ]]
代码相似度总和 (去除对角线): 6.19727143650317
代码相似度平均值 (去除对角线): 0.24789085746012682

算法描述相似度矩阵:
[[1.         0.43971291 0.4779723  0.4316553  0.40122844]
 [0.43971291 1.         0.46755662 0.49451975 0.41075629]
 [0.4779723  0.46755662 1.         0.46769916 0.3964182 ]
 [0.4316553  0.49451975 0.46769916 1.         0.50526602]
 [0.40122844 0.41075629 0.3964182  0.50526602 1.        ]]
算法描述相似度总和 (去除对角线): 8.98556997389778
算法描述相似度平均值 (去除对角线): 0.3594227989559112

--------------------------------------------------
对于文件 D:/00_Work/00_CityU/04_AEL_MEC/hle/results/hie/202412240058/sample_log.json:
代码相似度矩阵:
[[1.         0.50495833 0